import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/layout/TopPage.module.scss";
import Mv from "@/components/sections/top/Mv";
import Gallary from "@/components/sections/top/Gallary";
import Message from "@/components/sections/top/Message";

export default function Home() {
  return (
    <>
      <Head>
        <title>topページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div className={styles.container}>
          <Mv />
          <Gallary />
          <Message />
        </div>
      </main>

    </>
  );
}
