import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/layout/TopPage.module.scss";
import Mv from "@/components/sections/top/Mv";
import Gallery from "@/components/sections/top/Gallery";
import Message from "@/components/sections/top/Message";
import Circle from "@/components/sections/top/Circle";
import Enbu from "@/components/sections/top/Enbu";
import News from "@/components/sections/top/News";
import Sns from "@/components/sections/top/Sns";

export default function Home() {
  return (
    <>
      <Head>
        <title>topページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div className={styles.container}>
          <Mv />
          <Gallery />
          <Message />
          <Circle />
          <Enbu />
          <News />
          <Sns />
        </div>
      </main>

    </>
  );
}
